'use strict';
const crypto=require('crypto');const {prisma}=require('../database/prisma');const {hashPassword,verifyPassword}=require('../utils/password');const {ApiError}=require('../utils/response');const PUBLIC_USER_FIELDS={id:true,username:true,email:true,role:true,status:true,planName:true,lastLogin:true,createdAt:true,updatedAt:true};
async function createUser({username,email,password,role='user'}){const existing=await prisma.user.findFirst({where:{OR:[{email},{username}]}});if(existing)throw new ApiError('El usuario o correo electrónico ya está en uso.',409);const passwordHash=await hashPassword(password);return prisma.user.create({data:{username,email,passwordHash,role},select:PUBLIC_USER_FIELDS});}
async function findByIdentifier(identifier){return prisma.user.findFirst({where:{OR:[{email:identifier},{username:identifier}]}});}
async function authenticate(identifier,password){const user=await findByIdentifier(identifier);if(!user)throw new ApiError('Credenciales inválidas.',401);if(user.status==='suspended')throw new ApiError('Esta cuenta ha sido suspendida.',403);const valid=await verifyPassword(user.passwordHash,password);if(!valid)throw new ApiError('Credenciales inválidas.',401);await prisma.user.update({where:{id:user.id},data:{lastLogin:new Date()}});const {passwordHash,...safeUser}=user;return safeUser;}
async function getUserById(id){return prisma.user.findUnique({where:{id},select:PUBLIC_USER_FIELDS});}
async function listUsers({page=1,pageSize=20,search=''}={}){const where=search?{OR:[{username:{contains:search,mode:'insensitive'}},{email:{contains:search,mode:'insensitive'}}]}:{};const [items,total]=await Promise.all([prisma.user.findMany({where,select:PUBLIC_USER_FIELDS,orderBy:{createdAt:'desc'},skip:(page-1)*pageSize,take:pageSize}),prisma.user.count({where})]);return{items,total,page,pageSize,totalPages:Math.ceil(total/pageSize)};}
async function updateUserRole(userId,role){return prisma.user.update({where:{id:userId},data:{role},select:PUBLIC_USER_FIELDS});}async function updateUserStatus(userId,status){return prisma.user.update({where:{id:userId},data:{status},select:PUBLIC_USER_FIELDS});}async function updateUserPlan(userId,planName){return prisma.user.update({where:{id:userId},data:{planName},select:PUBLIC_USER_FIELDS});}async function setPassword(userId,newPassword){const passwordHash=await hashPassword(newPassword);return prisma.user.update({where:{id:userId},data:{passwordHash}});}
function createResetToken(){const rawToken=crypto.randomBytes(32).toString('hex');const tokenHash=crypto.createHash('sha256').update(rawToken).digest('hex');return{rawToken,tokenHash};}
async function requestPasswordReset(email){const user=await prisma.user.findUnique({where:{email}});if(!user)return null;const {rawToken,tokenHash}=createResetToken();const expiresAt=new Date(Date.now()+1800000);await prisma.passwordReset.create({data:{userId:user.id,tokenHash,expiresAt}});return{rawToken,user};}
async function resetPasswordWithToken(rawToken,newPassword){const tokenHash=crypto.createHash('sha256').update(rawToken).digest('hex');const record=await prisma.passwordReset.findUnique({where:{tokenHash}});if(!record||record.usedAt||record.expiresAt<new Date())throw new ApiError('El enlace de recuperación es inválido o ha expirado.',400);await setPassword(record.userId,newPassword);await prisma.passwordReset.update({where:{id:record.id},data:{usedAt:new Date()}});return true;}
module.exports={createUser,findByIdentifier,authenticate,getUserById,listUsers,updateUserRole,updateUserStatus,updateUserPlan,setPassword,requestPasswordReset,resetPasswordWithToken,PUBLIC_USER_FIELDS};
